version: "3.0"

services:
#  mysql:
#    image: honeysuckle_mysql
#    volumes:
#      - /var/lib/mysql:/var/lib/mysql
#      - ./deploy/mysql/my.cnf:/etc/mysql/my.cnf
#    ports:
#      - "3006:3006"
#    restart: always

#  redis:
#    build: ./deplay/redis
#    volumes:
#      - /var/lib/redis:/var/run/redus
#      - ./deplay/redis/redis.conf:/etc/redis/redis.conf
#    ports:
#      - "6379:6379"
#    restart: always
#  frontend:
#    build: ./frontend
#    volumes:
#      - /opt/honeysuckle/frontend/build/dist:/usr/share/nginx/html
  web:
    build: ./api
    volumes:
      - /opt/honeysuckle:/opt/honeysuckle
##      - mysql
#      - redis
#    links:
##      - mysql
#      - redis
#    depends_on:
#      - frontend
    restart: always
  nginx:
    build: ./deploy/nginx
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
    depends_on:
      - web
    restart: always