version: "3.0"

services:
#  mysql:
#    image: honeysuckle_mysql
#    volumes:
#      - /var/lib/mysql:/var/lib/mysql
#      - ./deploy/mysql/my.cnf:/etc/mysql/my.cnf
#    ports:
#      - "3006:3006"
#    restart: always

#  redis:
#    build: ./deplay/redis
#    volumes:
#      - /var/lib/redis:/var/run/redus
#      - ./deplay/redis/redis.conf:/etc/redis/redis.conf
#    ports:
#      - "6379:6379"
#    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        APP_ENV: development  # development or production
    image: honeysuckle-frontend:latest
    volumes:
      - ./frontend/dist:/opt/honeysuckle/frontend/dist
      - ./frontend/components:/opt/honeysuckle/frontend/components
      - ./frontend/pages:/opt/honeysuckle/frontend/pages

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        APP_ENV: development  # development or production
    image: honeysuckle-backend:latest
    volumes:
      - ./backend:/opt/honeysuckle/backend
      - uwsgi_socket:/var/run/honeysuckle
      - /var/logs:/var/logs
##      - mysql
#      - redis
#    links:
##      - mysql
#      - redis
#    depends_on:
#      - frontend
    ports:
      - "5000:5000"
    restart: always

  nginx:
    build:
      context: ./deploy/nginx
      dockerfile: Dockerfile
      args:
        APP_ENV: development  # development or production
    image: honeysuckle-nginx:latest
    volumes:
      - ./frontend:/opt/honeysuckle/frontend
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - uwsgi_socket:/var/run/honeysuckle
    ports:
      - "80:80"
#      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  uwsgi_socket: